function out1 = g_dynamics_Linearization_SSIM(in1)
%G_DYNAMICS_LINEARIZATION_SSIM
%    OUT1 = G_DYNAMICS_LINEARIZATION_SSIM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:38

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
s4 = in1(4,:);
s5 = in1(5,:);
s6 = in1(6,:);
t2 = -s2;
t3 = -s3;
t4 = -s5;
t5 = -s6;
t6 = s1+t2;
t7 = s1+t3;
t8 = s2+t3;
t9 = s4+t4;
t10 = s4+t5;
t11 = s5+t5;
t12 = cos(t6);
t13 = cos(t7);
t14 = cos(t8);
t15 = sin(t6);
t16 = sin(t7);
t17 = sin(t8);
t18 = t13./2.0;
t19 = t12.*(3.0./2.0);
t20 = t14./2.0;
t21 = t9.*t15.*(3.0./2.0);
t22 = (t10.*t16)./2.0;
t23 = (t11.*t17)./2.0;
t24 = -t21;
t25 = -t22;
t26 = -t23;
out1 = reshape([1.0,0.0,0.0,0.0,t24,t25,0.0,1.0,0.0,t24,0.0,t26,0.0,0.0,1.0,t25,t26,0.0,0.0,0.0,0.0,1.3e+1./4.0,t19,t18,0.0,0.0,0.0,t19,9.0./4.0,t20,0.0,0.0,0.0,t18,t20,5.0./4.0],[6,6]);
