function out1 = g_dynamics_ControlMap(in1)
%G_DYNAMICS_CONTROLMAP
%    OUT1 = G_DYNAMICS_CONTROLMAP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-May-2020 18:58:10

out1 = reshape([1.0,0.0,0.0,-1.0,1.0,0.0,0.0,-1.0,1.0],[3,3]);
