function out1 = g_dynamics_Linearization_RHS_c(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_C
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:38

out1 = [0.0;0.0;0.0;0.0;0.0;0.0];
