function out1 = g_dynamics_Linearization_RHS_A(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_A
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-May-2020 18:58:12

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0],[6,6]);
