function out1 = g_dynamics_RHS(in1,in2,in3)
%G_DYNAMICS_RHS
%    OUT1 = G_DYNAMICS_RHS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-May-2020 18:58:10

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q1-q2;
t3 = sin(t2);
t4 = v1-v2;
t5 = q1-q3;
t6 = sin(t5);
t7 = v1-v3;
t8 = q2-q3;
t9 = sin(t8);
t10 = v2-v3;
out1 = [u1-u2-v1+t3.*t4.*v2.*(3.0./4.0)+t6.*t7.*v3.*(1.0./4.0);u2-u3-v2+t3.*t4.*v1.*(3.0./4.0)+t9.*t10.*v3.*(1.0./4.0);u3-v3+t6.*t7.*v1.*(1.0./4.0)+t9.*t10.*v2.*(1.0./4.0)];
