function out1 = g_dynamics_JSIM(in1)
%G_DYNAMICS_JSIM
%    OUT1 = G_DYNAMICS_JSIM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:37

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = -q2;
t3 = -q3;
t4 = q1+t2;
t5 = q1+t3;
t6 = q2+t3;
t7 = cos(t4);
t8 = cos(t5);
t9 = cos(t6);
t10 = t8./2.0;
t11 = t7.*(3.0./2.0);
t12 = t9./2.0;
out1 = reshape([1.3e+1./4.0,t11,t10,t11,9.0./4.0,t12,t10,t12,5.0./4.0],[3,3]);
