function J1 = g_InverseKinematics_J1(in1)
%G_INVERSEKINEMATICS_J1
%    J1 = G_INVERSEKINEMATICS_J1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Jun-2020 16:53:23

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
J1 = reshape([cos(q1),-sin(q1),0.0,cos(q2),-sin(q2),0.0,cos(q3),-sin(q3),1.0],[3,3]);
