function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:57

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
Task = [cos(q1)+cos(q2)+cos(q3);sin(q1)+sin(q2)+sin(q3);q3];
