function J1 = g_InverseKinematics_J1(in1)
%G_INVERSEKINEMATICS_J1
%    J1 = G_INVERSEKINEMATICS_J1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:57

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
J1 = reshape([-sin(q1),cos(q1),0.0,-sin(q2),cos(q2),0.0,-sin(q3),cos(q3),1.0],[3,3]);
