function J2 = g_InverseKinematics_J2(in1,in2)
%G_INVERSEKINEMATICS_J2
%    J2 = G_INVERSEKINEMATICS_J2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:57

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
J2 = reshape([-v1.*cos(q1),-v1.*sin(q1),0.0,-v2.*cos(q2),-v2.*sin(q2),0.0,-v3.*cos(q3),-v3.*sin(q3),0.0],[3,3]);
