function rC = g_rC(in1)
%G_RC
%    RC = G_RC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Aug-2020 21:45:40

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
rC = [cos(q1).*(5.0./6.0)+cos(q2)./2.0+cos(q3)./6.0;0.0;sin(q1).*(5.0./6.0)+sin(q2)./2.0+sin(q3)./6.0];
