function rC = g_rC(in1)
%G_RC
%    RC = G_RC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    26-Apr-2020 21:12:29

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
rC = [sin(q1).*(1.0./2.0)+sin(q2).*(3.0./1.0e1)+sin(q3).*(1.0./1.0e1);0.0;cos(q1).*(1.0./2.0)+cos(q2).*(3.0./1.0e1)+cos(q3).*(1.0./1.0e1)];
